name: wm-tools
services:
  frontend:
    hostname: frontend
    build:
      context: ../..
      dockerfile: frontend/Dockerfile.dev
      args:
        VITE_SCRIPT_API_URL: ${SCRIPT_API_URL}
        VITE_SCRIPT_FRONTEND_URL: ${SCRIPT_FRONTEND_URL}
        VITE_SCRIPT_ILPAY_URL: ${SCRIPT_ILPAY_URL}
        VITE_INIT_SCRIPT_URL: ${SCRIPT_EMBED_URL}
    ports:
      - '5100:5100'
    expose:
      - '5100'
    environment:
      PORT: 5100
      NODE_ENV: development
      API_URL: ${API_URL}
      ILPAY_URL: ${SCRIPT_ILPAY_URL}
      FRONTEND_URL: ${SCRIPT_FRONTEND_URL}
      INIT_SCRIPT_URL: ${SCRIPT_EMBED_URL}
      OP_KEY_ID: ${OP_KEY_ID}
      OP_PRIVATE_KEY: ${OP_PRIVATE_KEY}
      OP_WALLET_ADDRESS: ${OP_WALLET_ADDRESS}
      OP_REDIRECT_URL: ${OP_REDIRECT_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
      AWS_RETRY_MAX_ATTEMPTS: ${AWS_RETRY_MAX_ATTEMPTS}
      AWS_RETRY_TIMEOUT: ${AWS_RETRY_TIMEOUT}
    networks:
      - wm-tools
    command: pnpm run dev
    # depends_on:
    #   - backend
    volumes:
      - ../../certs:/app/certs
      - ../../frontend:/app/frontend
      - /app/frontend/node_modules

networks:
  wm-tools:
    driver: bridge
