name = "publisher-tools-embed"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public"
binding = "ASSETS"

[vars]
VITE_SCRIPT_FRONTEND_URL = "https://frontend-url/"
VITE_SCRIPT_API_URL = "https://api-url/"
VITE_SCRIPT_ILPAY_URL = "https://ilpay-url/"