name = "publisher-tools"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-05-05"
main = "worker.ts"
upload_source_maps = true

[assets]
directory = "./build/client"

[dev]
port = 3001

[vars]
SCRIPT_ILPAY_URL = "https://interledgerpay.com/extension/"
SCRIPT_EMBED_URL = "https://cdn.webmonetization.org/"
