name = "publisher-tools-api"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-09-23"
pages_build_output_dir = "./build/client"

[dev]
port = 5102

[vars]
SCRIPT_ILPAY_URL = "https://interledgerpay.com/extension/"
SCRIPT_EMBED_URL = "https://cdn.webmonetization.org/"
