name = "web-monetization-tools"
main = "functions/[[worker]].ts"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"

[dev]
port = 5100

[site]
bucket = "./public"

[env.production]
vars = { NODE_ENV = "production" }

[env.development]
workers_dev = true
vars = { NODE_ENV = "development" }