name = "publisher-tools"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-05-05"
main = "worker.ts"
upload_source_maps = true

kv_namespaces = [
  { binding = "INTERACTION_KV", id = "interaction_kv", preview_id = "preview_interaction_kv" }
]

[assets]
directory = "./build/client"

[observability.logs]
enabled = true
invocation_logs = true
head_sampling_rate = 1.00

[dev]
port = 3001
