packages:
  - 'api'
  - 'frontend'
  - 'cdn'
  - 'components'
  - 'shared/*'
  - 'localenv/*'

allowBuilds:
  '@actions/github-script@https://codeload.github.com/actions/github-script/tar.gz/ed597411d8f924073f98dfc5c65a23a2325f34cd': true
  esbuild: true
  sharp: true
  workerd: true

overrides:
  esbuild: ^0.28.1
  wrangler: ^4.100.0
