name: Bug report
description: File a bug report
title: '[BUG] '
labels: ['bug', 'triage']
type: Bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Explain how the behavior can be reproduced.
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. Click on '...'
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected result
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual result
      description: A clear and concise description of what is happening.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or videos
      description: If applicable, add screenshots and/or a short video to help explain your problem.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.

  - type: dropdown
    id: component
    attributes:
      label: Affected component
      description: Which component of the Web Monetization Tools are you having issues with?
      multiple: true
      options:
        - Payment Button
        - Monetization Widget
        - Banner
        - Revenue Share
        - Others
    validations:
      required: true

  - type: dropdown
    id: device-type
    attributes:
      label: Device type
      description: What type of device are you using?
      multiple: false
      options:
        - Desktop
        - Mobile
        - Tablet
        - Other
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: Operating system version
      description: What version of the operating system(s) are you seeing the problem on?

  - type: dropdown
    id: browsers
    attributes:
      label: Browsers
      description: What browser(s) are you seeing the problem on?
      multiple: true
      options:
        - Chrome
        - Safari
        - Firefox
        - Brave
        - Microsoft Edge
        - Opera
    validations:
      required: true

  - type: input
    id: browser-version
    attributes:
      label: Browser version
      description: What version of the browser(s) are you seeing the problem on?
